repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.21
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        # Override default --ignore-missing-imports
        # Use pyproject.toml if possible instead of adding command line parameters here
        args: [ --warn-unused-configs ]
        additional_dependencies:
          # Keep in sync with the `typecheck` dependency group in pyproject.toml
          # Type stubs
          - types-docutils
          - types-PyYAML
          - types-setuptools
          # Typed libraries
          - pytest
          - cloudpickle
  - repo: https://github.com/scientific-python/cookie
    rev: 2026.04.04
    hooks:
      - id: sp-repo-review

ci:
  # To trigger manually, comment on a pull request with "pre-commit.ci autofix"
  autofix_prs: false
  autofix_commit_msg: "style: pre-commit.ci auto fixes [...]"
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_schedule: "monthly"
  skip: []
